trigger:
- main

jobs:
  - job: linux
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
        Python38:
          python.version: '3.8'
        Python39:
          python.version: '3.9'
        Python310:
          python.version: '3.10'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        # ubuntu 18.04 minimum for libeccodes-dev
        sudo apt-get install -y libeccodes-dev proj-bin libproj-dev libcairo2-dev
        # TODO: add cairo for both ubuntu and centos
        # CentOS: eccodes-devel proj proj-devel cairo-devel
      displayName: 'install OS packages'

    - script: |
        curl 'https://zenodo.org/record/3406483/files/am-11.0.tgz?download=1' > am-11.0.tgz
        #curl 'https://zenodo.org/record/5794524/files/am-12.0.tgz?download=1' > am-12.0.tgz
        tar xf am-11.0.tgz
        cd am-11.0/src
        make serial
        cd ../..
        ./am-11.0/src/am -v
      displayName: 'install am-11.0'

    - script: |
        python -m pip install --upgrade pip
        pip --use-feature=in-tree-build install . .[test]
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-azurepipelines
        export AM=./am-11.0/src/am
        PYTHONPATH=. pytest --cov-report=xml --cov=eht_met_forecast -v -v
        coverage report -m
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)

  - job: macos
    pool:
      vmImage: 'macOS-latest'
    strategy:
      matrix:
        Python38:
          python.version: '3.8'

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - script: |
        brew install eccodes proj cairo
      displayName: 'install OS packages'

    - script: |
        curl 'https://zenodo.org/record/3406483/files/am-11.0.tgz?download=1' > am-11.0.tgz
        #curl 'https://zenodo.org/record/5794524/files/am-12.0.tgz?download=1' > am-12.0.tgz
        tar xf am-11.0.tgz
        cd am-11.0/src
        make serial
        cd ../..
        ./am-11.0/src/am -v
      displayName: 'install am-11.0'

    - script: |
        # see brew above for where OS packages are installed
        python -m pip install --upgrade pip
        # XCode 12 makes this warning an error? the function is in cython-generated code
        export CFLAGS="-Wno-implicit-function-declaration"
        pip --use-feature=in-tree-build install . .[test]
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-azurepipelines
        export AM=./am-11.0/src/am
        touch tests/__init.py__
        PYTHONPATH=. pytest --cov-report=xml --cov=eht_met_forecast -v -v
        coverage report -m
      displayName: 'pytest'

    - script: |
        pip install coveralls
        export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
        coveralls
      displayName: 'coveralls'
      env:
        CIRCLECI: 1
        CIRCLE_BUILD_NUM: $(Build.BuildNumber)
        COVERALLS_REPO_TOKEN: $(coveralls_repo_token)
